### ISSUE TITLE
Local development workflow unexplained/error

### ISSUE THREAD

**Issue by mikedotexe** [near/create-near-app#106]
For a contributor to this Github project, it's unclear how exactly to test code locally.
I also believe there's a bug somewhere that could be quite confusing to folks.

**Problem**:
Contributors need to pull this code down, test locally, and then submit a PR for features. Some functionality works when installing through the package (like by `npx …` commands) but do not work locally when running `node index.js mydirectory`.

I am seeing this error:
```
Uncaught (in promise) Error: Querying call/dev-1582068317359/welcome failed: wasm execution failed with error: FunctionCallError(HostError(GuestPanic("Value with Key: account_id is not a string or null, filename: \"nearFile\" line: 345 col: 2"))).
{
  "block_height": 571940,
  "error": "wasm execution failed with error: FunctionCallError(HostError(GuestPanic(\"Value with Key: account_id is not a string or null, filename: \\\"nearFile\\\" line: 345 col: 2\")))",
  "logs": []
}
    at JsonRpcProvider.query (json-rpc-provider.js:36)
    at async Account.viewFunction (account.js:160)
```

when I try to run locally.
However, I am able to test code locally after doing an `npm pack` command. This is very strange and should certainly be documented or fixed.

**Steps to reproduce problem**:

`git clone git@github.com:nearprotocol/create-near-app.git`
`cd create-near-app`
`npm i`
`node index.js myaccountid`
`cd myaccountid`
`npm i`
`near login`
`npm run start`
Try logging in, you'll see the error above.

**Steps to reproduce odd workflow that works**:
`git clone git@github.com:nearprotocol/create-near-app.git`
`cd create-near-app`
`npm pack`
look for tarball, put that somewhere else, extract it…
`npm i`
`node index.js myaccountid`
`cd myaccountid`
`npm i`
`near login`
`npm run start`
Try logging in, and it works.

**Comment by chadoh** [comment]
The development workflow has been greatly improved with the merge of #386 (and addendum 9f29c9cdbe73442af0c05550da08812323647d74)
