### ISSUE TITLE
Add 'change' method examples to templates

### ISSUE THREAD

**Issue by kcole16** [near/create-near-app#109]
Currently, the templates demonstrate logging in with the web wallet and calling a `view` method, but do not show how to call a `change` method and modify state.

At a minimum, we should demonstrate a `change` method using the locally stored limited access key (returned during `Login`).

### Acceptance Criteria
- [x] Templates contain a `change` method example with user input
- [ ] Templates contain `change` method with a NEAR deposit attached

**Comment by janedegtiareva** [comment]
The purpose of the starter apps in create-near-app was supposed to be "bare bones example to get started quickly".
