### ISSUE TITLE
Create React App support

### ISSUE THREAD

**Issue by mrrobot16** [near/create-near-app#1098]
Was there a particular reason to not use the https://www.npmjs.com/package/create-react-app package?

**Comment by DiscRiskandBisque** [comment]
I wasn't around for this design decision, but there's no technical reason preventing `create-react-app` from being the basis of a NEAR dapp. If I were to venture a guess, I'd say parcel's zero-config setup and generally providing a more lightweight project were the reasons. @mikedotexe might have more to add here.

Would you be interested in creating a `create-react-app` + NEAR starter/boilerplate?

**Comment by chadoh** [comment]
I suggest we keep `create-near-app` unchanged, but add a `create-react-app` [custom template](https://create-react-app.dev/docs/custom-templates). This would allow people who want to use create-react-app to issue a command like:

    npx create-react-app my-app --template near

To make this possible, we would need to publish a `cra-template-near` package to NPM.

Before we build such a thing, though, we need to decide who will maintain this template library. If we build the initial implementation, would you be willing to keep it up-to-date, @mrrobot16?

**Comment by gagdiez** [comment]
We will keep it without `create-react-app` since in this way it is simpler for us to maintain and reduce boilerplate to a maximum.
