### ISSUE TITLE
PostCSS plugin tailwindcss requires PostCSS 8

### ISSUE THREAD

**Issue by Aybee5** [near/create-near-app#1209]
I created an app using `npx create-near-app my-app` after creating the app I run the local server but getting `<rootDir>/my-app/src/global.css:undefined:undefined: PostCSS plugin tailwindcss requires PostCSS 8.`
 I tried reinstalling `postcss@^7` but still getting the error.
 Node version - 14.17.3

**Comment by 0xBarro** [comment]
Also trying to use Tailwind and having this dependency issue. Did you make any progresss on this?
