### ISSUE TITLE
gitignore file bug

### ISSUE THREAD

**Issue by icerove** [near/create-near-app#127]
find out two questions for .gitignore in create-near-app.
1. when create rust vanilla project the .gitignore file is just near.gitignore file and another real .gitignore file content is not in the .gitignore file. The obvious one is that /.cache is not in it.
2. For rust react file, no .gitignore file

**Comment by janedegtiareva** [comment]
I could not reproduce! I just tested this on top of tree, and it works properly (I see .gitgnore in the new directory)

**Comment by icerove** [comment]
it has .gitignore, but the content of it is near.gitignore, not the combination of .gitignore and near.gitignore

**Comment by janedegtiareva** [comment]
That's intended. near.gitignore and .gitignore are identical.
