### ISSUE TITLE
"Sorry, assemblyscript is not supported in your system, use --contract=rust " error in NEAR. Suggest me to use rust instead of assemblyscript when i give assemblyscript in command

### ISSUE THREAD

**Issue by sametmollaoglu** [near/create-near-app#1850]
I just want to use create-near-app package from the npm registry as assemblyscript and react. But it gives https://i.stack.imgur.com/Lx36I.png error, how can i fix that ?

**Comment by MaxGraey** [comment]
That's due to this changes:
https://github.com/near/create-near-app/commit/dd8ac16f74dc231c94c12a423ebafd60e1dda3bd#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R62

which means if your system is not 64-bit MacOS or Linux you should use Rust instead AS.
@gagdiez but why?

**Comment by MaxGraey** [comment]
If you want to avoid Apple's M1 better use this detection algorithm:
```js
const os = require('os');

const isM1 = return os.cpus()[0].model.includes("Apple");

const support_sandbox = !isM1
```

**Comment by MaxGraey** [comment]
Also it will be great to make a reference to this issue https://github.com/near/workspaces-rs/issues/110

**Comment by MaxGraey** [comment]
@gagdiez this error described in https://github.com/near/workspaces-rs/issues/110. It also affects to Rust template. I proposed a solution. Just properly detect M1 arch as descibed [here](https://github.com/near/create-near-app/issues/1850#issuecomment-1189929277). And plz remove unnecessary message "Sorry, assemblyscript is not supported in your system, use --contract=rust" which compleately block all users which use 32/64-bit windows for ANY platform

**Comment by gagdiez** [comment]
sure, we are currently working on the new release, will see to change the message to "Sorry, NEAR-SDK-AS is not supported in your system" by then.

Thanks for the heads up!

**Comment by gagdiez** [comment]
@sametmollaoglu @MaxGraey the latest version of `create-near-app` has just been released, which enables assemblyscript in Mac and Linux. Our tool does not have support for windows, for which you cannot use it to start a NEAR project.

You can try it now using `npx create-near-app` and that will download version 4.0.0.

**Comment by volovyk-s** [comment]
I will clarify info about Windows support: you can use all our tools if you are in the Windows subsystem for Linux.
