### ISSUE TITLE
Suggestion - remove rust installation script

### ISSUE THREAD

**Issue by maxhr** [near/create-near-app#1851]
I think automatic installation of rust toolchain should be completely removed from this tool, because -
1. This is too low-level-system thing and it's always dangerous
2. If someone wants to develop Rust, he should already have the toolchain
3. Even if we have a dev that this is the first time he ever sees Rust, the best way to learn new language workflows and toolchains is from the actual Rust docs site, there he'll find explanation about what is `rustup` and targets and so on.. We shouldn't do any magic installations for him

We only should have a message saying that you need `wasm32-unknown-unknown` target and link to the Rust docs page about it.

@volovyk-s @gagdiez wdyt?

**Comment by gagdiez** [comment]
I agree, lets simply detect if the user has Rust installed, and warn them if not.

**Comment by volovyk-s** [comment]
Ok, we can get rid of this magic. But let's make sure we point users to the Rust doc that will help them to install everything they need.
