### ISSUE TITLE
Create near app issue

### ISSUE THREAD

**Issue by ychrisbishop** [near/create-near-app#1883]
I tried to create near boilerplate by create-near-app, but having such error and can't create near template
![image](https://user-images.githubusercontent.com/91833579/184965280-4648d206-26e4-45f2-8d0b-52e6f3795676.png)

**Comment by gagdiez** [comment]
Hi @ychrisbishop, I don't see any error in the image. The program is stating:

"on windows please use wsl"

that's because we don't have support for windows. Instead please, use wsl.

**Comment by ychrisbishop** [comment]
![image](https://user-images.githubusercontent.com/91833579/185099157-9b4e13b2-df48-4370-9f4f-79edc566c597.png)
I am trying to login by near wallet. But it doesn't go forward from this screen. stop this screen and don't switch to success url. how can i solve this issue?
