### ISSUE TITLE
Near login wallet error

### ISSUE THREAD

**Issue by ychrisbishop** [near/create-near-app#1884]
![image](https://user-images.githubusercontent.com/91833579/185099676-3e06cdd6-1a93-4d6e-b258-37d80ab6ec3f.png)
I am trying to login by near wallet. But it doesn't go forward from this screen - just loading forever. stop this screen and don't switch to success url. how can i solve this issue?

**Comment by ychrisbishop** [comment]
![image](https://user-images.githubusercontent.com/91833579/185101137-4784aebf-891c-4e5e-9b56-dd87ea2dc913.png)

**Comment by gagdiez** [comment]
Interesting, that seams to be a problem with the wallet more than with NEAR app. Try to reload the page a couple of times to see if it clears some broken scripts.
