### ISSUE TITLE
Update Rust template to use ABI to connect frontend with contract

### ISSUE THREAD

**Issue by austinabell** [near/create-near-app#1912]
This likely won't be super straightforward since the frontend code would have to be modified to conditionally use the ABI if Rust or not.

Dependent on https://github.com/near/near-abi-client-js/issues/8, and probably best to do it after an example has been ported over (to make the pattern clear).

cc @itegulov @miraclx

**Comment by gagdiez** [comment]
`cargo near build` now creates contracts with ABI

**Comment by gagdiez** [comment]
cargo near build now adds abi automatically for rust contracts
