### ISSUE TITLE
No option to create-near-app in a blank folder

### ISSUE THREAD

**Issue by weiler1** [near/create-near-app#1956]
I am looking for something like **_create-near-app ._** that assumes the name of the enclosing folder and doesn't create one additional project folder underneath, similar to **_npx create-react-app ._**

Is there any way to do this with create-near-app, or can this be included in a subsequent update?

**Comment by gagdiez** [comment]
hi @weiler1, what do you mean by "that assumes the name of the enclosing folder" ? I am not understanding the expected behaviour.

**Comment by subashcs** [comment]
Do you (@weiler1) mean we can't do something like this?

```
npx create-near-app . --contract js --frontend react --tests js
```

**Comment by gagdiez** [comment]
we are not planning to add this, since it would add extra logic and complexity to a project that is being supported by only one person (me)
