### ISSUE TITLE
Permissions required for everything including running commands

### ISSUE THREAD

**Issue by Charl00** [near/create-near-app#2007]
Hi

For some reason I need sudo permissions accompanied by each and everything I do from file edits to running commands. 

I tested against all my other projects and none of them require this sort of permission handling. The NEAR project was created using the create-near-app command. I do have permissions to the directories above.

I created it this morning so everything should be latest of latest.

Let me know if there is anything I can add to help .

| File edits | Commands run |
| ---- | ---- |
| ![image](https://github.com/near/create-near-app/assets/36984065/3e5d200c-10b4-4c2c-8dce-32751f62eab3) | ![image](https://github.com/near/create-near-app/assets/36984065/298832f2-dd4e-4037-8069-222af1439190) |

**Comment by agostbiro** [comment]
Hi @Charl00, thanks for reporting this! 

One thing that comes to mind that could cause this behavior is if you possibly ran `create-near-app` in the Windows Subsystem for Linux but then tried to run it from Windows or the other way around. Do you remember if that was the case?

**Comment by gagdiez** [comment]
I agree that this not seams to be an error of the tool, for which I am closing this issue, please open again if pertinent.
