### ISSUE TITLE
Readme and cli supported templates are not in sync

### ISSUE THREAD

**Issue by serkonda7** [near/create-near-app#2110]
Version `6.0.0`

The CLI states the following supported templates:
```
Run npx create-near-app without arguments, or use:
npx create-near-app <projectName> --frontend next|vanilla|none --contract rs|ts|none --tests rs|ts|none
```

However the readme lists JS, RS and AS contracts plus React and vanilla frontend.

These should be kept in sync to avoid confusion

**Comment by gagdiez** [comment]
thanks for noticing, it should be fixed now
