### ISSUE TITLE
npm install fails for React frontend

### ISSUE THREAD

**Issue by serkonda7** [near/create-near-app#2112]
Seems to be an issue with node-gyp.

This should be fixed or possible other prerequisites should be mentioned in the docs.

The log is attached
[2023-11-12T19_24_21_081Z-debug-0.log](https://github.com/near/create-near-app/files/13329137/2023-11-12T19_24_21_081Z-debug-0.log)

**Comment by gagdiez** [comment]
hi @serkonda7, thanks for reporting!

The log is a bit long and is basically showing that something was not being correctly compiled. Could you give me some insight into the context? (OS, node version, npm version)

**Comment by serkonda7** [comment]
running `pnpm install` the issue did not occur.

If you still need the cntext:
```
Arch Linux
Node 21.1.0
npm 10.2.3
pnpm 8.10.5
```
