### ISSUE TITLE
Broken tutorial macos

### ISSUE THREAD

**Issue by madroneropaulo** [near/create-near-app#2123]
I'm following this tutorial. I'm choosing the js/ts contract option.
https://docs.near.org/develop/quickstart-guide
so a few things:

1. the console shows different options than the tutorial. Instead of `npm start` it shows `npm run test`
2. the script `start` doesn't exist in the package.json so I follow the console instructions.
3. I'm getting an error
```
 Uncaught exception in ../build/hello_near.wasm

  /Users/user/projects/hello-near/build/hello_near.wasm:1



  SyntaxError: Invalid or unexpected token

  › SyntaxError: Invalid or unexpected token
  › require.extensions.<computed> (node_modules/ts-node/src/index.ts:1608:43)
```

**Comment by gagdiez** [comment]
Thanks for reporting, the tutorial was superseded by: https://docs.near.org/develop/contracts/quickstart
