### ISSUE TITLE
npm run test fails

### ISSUE THREAD

**Issue by danmesfin** [near/create-near-app#2126]
I followed the instructions to create smart contrat from here(https://docs.near.org/develop/contracts/quickstart)

app created successful.

Build was also successful.
 `[transpileJsAndBuildWasm] › ✔ success   Generated build/hello_near.wasm contract successfully!`

npm run test keeps failing 

here is the error message

```
> ava-testing@1.0.0 test
> ava ../build/hello_near.wasm

Uncaught exception in ../build/hello_near.wasm

  ~/~/dev/hello-near-sm/build/hello_near.wasm:1

  SyntaxError: Invalid or unexpected token

  › SyntaxError: Invalid or unexpected token
  › require.extensions.<computed> (node_modules/ts-node/src/index.ts:1608:43)

  ✘ ../build/hello_near.wasm exited with a non-zero exit code: 1
  ─

  1 uncaught exception
```

node v20.11.0
npm v10.2.4

**Comment by AlexKushnir1** [comment]
I advise you to use the test sript from package.json it is called like this: npm run test or add "--" after ava in your call and pass the correct file path!

**Comment by gagdiez** [comment]
the test is working on multiple node versions: 
https://github.com/near/create-near-app/blob/master/.github/workflows/test-contract-ts.yml
