### ISSUE TITLE
[ERROR] create-near-app don't work!

### ISSUE THREAD

**Issue by KimCookieYa** [near/create-near-app#2131]
![image](https://github.com/near/create-near-app/assets/45006957/6a35d1cc-6a53-48cf-8904-e967a1596e68)

Environment: wsl + node 18.17.1 or node 20.11.0

I looked at the docs and installed it, but an error popped. I was told to use the latest nodejs, so I installed it, but it still doesn't work. What's the problem?

![image](https://github.com/near/create-near-app/assets/45006957/d8a1a19a-5c75-4ba6-8e69-42c9675d5a9f)

**Comment by gagdiez** [comment]
this is fixed now, turns out one of our dependencies was not compatible with new versions of node

we contributed fixes to the dependency to fix this

**Comment by KimCookieYa** [comment]
Thank you!
