### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by arhansuba** [near/create-near-app#2137]
How can we ceate mobile app for near ecosystem with this repo can I use mobile app frameworks for frontend folder?

**Comment by gagdiez** [comment]
create-near-app does not offer any mobile framework, and I am not planning to add any new framework since I do not have the bandwith to do so. However, if you have the time and the knowledge, any contribution is highly appreciated

**Comment by arhansuba** [comment]
I kinda have a problem here I can not understand in any doc there is
nothing for mobile development for near blockchain but there is mobile near
app so I kinda guess I think it will work with http requests like on mobile
frontend user clicks button frontend interact with backend to contracts

11 Nis 2024 Per, saat 17:39 tarihinde gagdiez ***@***.***>
şunu yazdı:

**Comment by gagdiez** [comment]
I do not know what the people behind the mobile app used, sorry for not having an answer
