### ISSUE TITLE
Bounty: Issue: Error Build when running npm run dev after npx create-near-app

### ISSUE THREAD

**Issue by Amira1502** [near/create-near-app#2161]
### What talent are you looking for?

Development

### What you need to be done?

**Description:**
I encountered an error while running the command npm run dev after creating a project using npx create-near-app. The build failed with the following error message:

![image](https://github.com/user-attachments/assets/7ac9c907-8b61-4439-b25b-a8f36ac1af30)

**Steps to Reproduce:**

1. Run npx create-near-app to create web app 
2. After the project is generated, run npm install.
3. Execute npm run  dev.

**Expected Behavior:**
The development server should start without any issues 

**Actual Behavior:**
The build fails with a compilation error related to the @wagmi/core package.

**Possible Cause:**
It seems that the version of @wagmi/core being used in the project has changed its exports, and extractRpcUrls is no longer available, or the package has not been updated to reflect the change.

**Environment:**
Node.js version: 20
Next.js version: 14.2.13
OS: Windows

**Possible Fixes:**
Updating to a compatible version of @wagmi/core or ensuring that the package correctly exports extractRpcUrls.
Modifying the code in metaMask.js to handle the change in the exports.

### Tags

dApp, Quality Assurance

### Deadline

19.05.2025

### Currency

USDt

### Amount

100

### KYC

- [x] Use KYC Verification

**Comment by aybanda** [comment]
Hello @Amira1502 and  @near team,

I'm happy to report that I've successfully recreated the project using create-near-app, and it's working well without encountering the reported error. Here are the details of my environment and process:

Environment:
- Node.js version: [v18.20.4]
- npm version: [10.7.0]
- Operating System: [macOS   ProductVersion: 14.6.1     BuildVersion: 23G93]

Steps I followed:

1. Ran `npx create-near-app@latest` [ Initially tried it with 'npx create-near-app' encountered problems.]
2. Followed the prompts to create a new project
3. Navigated to the project directory
4. Ran `npm install`
5. Executed `npm run dev`

The project started successfully without any errors related to `@wagmi/core` or `extractRpcUrls`.

I want to note that I couldn't replicate the exact scenario from the original report using `npx create-near-app` without the `@latest` tag.

It seems that the issue might have been resolved in a recent update or may be environment-specific. I hope this information is helpful for closing this issue.

Regarding the bounty, I believe I've successfully resolved the reported problem by verifying that the current version of create-near-app works correctly. Please let me know if you need any additional information or if there are any other steps I should take to claim the bounty.

'near-app' running successfully without errors:

<img width="1440" alt="Screenshot 2024-10-25 at 1 17 52 PM" src="https://github.com/user-attachments/assets/3f033f44-2a79-4331-89a5-ca6c63b9101c">


<img width="1440" alt="Screenshot 2024-10-25 at 1 08 34 PM" src="https://github.com/user-attachments/assets/23eb2b1c-5454-40a9-a098-a05144a5968d">

**Comment by Amira1502** [comment]
Hello @aybanda,

Thank you for the detailed feedback and for verifying the issue in your environment. It’s great to know that create-near-app@latest worked as expected for you, with no errors related to @wagmi/core or extractRpcUrls. Your insights on environment-specific differences are particularly valuable.
Unfortunately, I'm still experiencing the issue in my setup, which runs in a WSL environment on Windows 11. Here are my environment details:
- Node.js version: 18.18.0
- Operating System: WSL (Ubuntu) on Windows 11

I encountered the same error when using npx create-near-app@latest.

![image](https://github.com/user-attachments/assets/676a0e1d-0ee2-4f60-a89d-6f647035a4cb)


![image](https://github.com/user-attachments/assets/6284648e-c7d8-4ab5-9e4c-442aa4a23872)

This issue seems to be specific to certain environments, as it appears under WSL but not on macOS.

**Update:** I found a temporary workaround that resolved the issue in my environment:

1. Removed node_modules with rm -rf node_modules
2. Copy code : npm install @wagmi/connectors@latest @wagmi/core@latest

![image](https://github.com/user-attachments/assets/320b6624-42de-44d0-afc2-2777d615f256)

While I was able to get the project running with these adjustments, I’m still experiencing intermittent issues in my WSL environment. 
Please let me know if you need any additional information or if there are any further steps I should take to proceed with the bounty claim.

Thank you for your support!
Best,
Amira

**Comment by aybanda** [comment]
Hey @Amira1502  It's great that you found a temporary fix. For a more permanent solution to those intermittent WSL issues, here are a few key things to try:

1. Update WSL and Ubuntu: Run `wsl --update` and `sudo apt update && sudo apt upgrade`.

2. Ensure Node.js consistency: Use nvm to manage Node versions. Install it with:
   `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash`
   Then use `nvm install --lts` and `nvm use --lts`.

3. Try `npm ci` instead of `npm install` to ensure exact dependency versions.

4. Create a .npmrc file in your project root with:
   ```
   save-exact=true
   package-lock=true
   ```

These steps should help stabilize your environment. If you're still having trouble, let us know the specific errors you're seeing. The NEAR team might also have some WSL-specific insights to share.

Thank you for the clarification about the issue and the workaround you've found, Amira1502. It's great to see progress being made.

Regarding the 100 USDT bounty mentioned in the issue description, I'm not entirely sure about the process for claiming it or if my contribution qualifies. Could someone from the @near team provide some guidance on this? I'm happy to have helped troubleshoot the issue, but I want to make sure I understand the next steps, if any, for the bounty consideration.

In the meantime, I'm glad we've made some headway on this problem. If there's anything else I can do to help further, please let me know!

**Comment by gagdiez** [comment]
@Amira1502  could I get some clarification on this "bounty", as far as I know, the NEAR Foundation nor anyone in the NEAR team is paying for bounties on any repository

Are you part of some NEAR team? where is that 100 USDT that you are offering coming from?

**Comment by Amira1502** [comment]
@gagdiez Thanks for your question! I found an issue with the **create.near app** on Windows and spent 10 hours manually testing all the test cases, which is where the **10h = $10** comes from. That’s what I meant by the bounty.  

However, I’m not sure how the process works with the NEAR Foundation. I came across the **Simple Bounty** template on GitHub, which seemed like a way to report and track contributions, but I’m still unclear about how everything fits together.  

![image](https://github.com/user-attachments/assets/0a8cdc7a-17ce-4347-84de-45689b07875f)

If there’s a way, I’d love to contribute more to NEAR, but I’m a bit lost on where to start. Any guidance or resources you could share would be greatly appreciated!

**Comment by gagdiez** [comment]
hello @Amira1502 and @aybanda, I would like to clarify the situation. 

Apparently @Amira1502 opened this issue thinking it would be a way to get some rewards for their contributions. In other words, @Amira1502 was not intending to pay somebody to fix the problem, but instead was trying to start contributing to the ecosystem, and be paid meanwhile.

I will close this issue to avoid any further complications.

Thank you both for being part of the ecosystem, and do not hesitate to reach out to our DevRel team at the NEAR DEV channel if you need anything.
