### ISSUE TITLE
`Yarn dev` fails if RPC is unresponsive

### ISSUE THREAD

**Issue by jimmy3dita** [near/create-near-app#252]
I'm a BetaNet lover - and there the RPC server (https://rpc.betanet.nearprotocol.com) is often unresponsive (e.g. error 500).
Therefore, the command `yarn dev` fails mid-flight when I try to deploy an application.

Workaround:
Manually modify `package.json` at line 8, changing to `near dev-deploy --nodeUrl http://xx.yy.zz.aa:3030`

Potential solutions\examples:
- Pass a custom --nodeUrl
- Ask to retry the command or abort the process
- Keep the state, and restart the deployment from that very step

**Comment by janedegtiareva** [comment]
This is most likely fixed. Please reopen if the problem is still happening.
