### ISSUE TITLE
Offer to install Rust automatically

### ISSUE THREAD

**Issue by vgrichina** [near/create-near-app#374]
Instead of merely sending users to install Rust based on docs (https://docs.near.org/docs/roles/developer/contracts/near-sdk-rs#pre-requisites) we can detect whether Rust is installed and offer to do it automatically otherwise. 

Workflow is roughly:
1. Check if `rustup` is available, offer to install otherwise.
2. Check if `wasm32-unknown-unknown` target is available, offer to install otherwise.

Offer to install can be something like this:

```
To build Rust smart contracts you need to install Rust compiler for WebAssembly. We can run following command to do it:

     rustup target add wasm32-unknown-unknown

Continue with installation? [yes]:
```

**Comment by mikedotexe** [comment]
really good idea
