### ISSUE TITLE
support yarn create

### ISSUE THREAD

**Issue by robert-zaremba** [near/create-near-app#375]
`npx` works only with `npm`

Let's add a support to yarn: `yarn create create-near-app`.

**Comment by chadoh** [comment]
@robert-zaremba would you like to see this in the README only, or somewhere else as well?

**Comment by robert-zaremba** [comment]
`yarn create create-near-app` doesn't work last time I checked. I think you need to register the app in yarn repo to make this work.

**Comment by chadoh** [comment]
@robert-zaremba you can run `yarn create near-app`

**Comment by robert-zaremba** [comment]
This works!

**Comment by robert-zaremba** [comment]
I've created a PR: https://github.com/near/create-near-app/pull/404

**Comment by chadoh** [comment]
:boom:
