### ISSUE TITLE
Move asc files to common/contracts/

### ISSUE THREAD

**Issue by chadoh** [near/create-near-app#402]
We currently have AssemblyScript kruft in generated Rust projects:

* `asconfig.js`
* `as-pect.config.js`

This is confusing for people building Rust projects

It's also confusing for people building with AssemblyScript, since these files are in the root of the project directory, rather than being nested within the `assembly` folder where they belong

**Comment by chadoh** [comment]
Related: https://github.com/AssemblyScript/assemblyscript/pull/1238

**Comment by willemneal** [comment]
`asconfig.js` soon to be `asconfig.json` is akin to a Cargo.toml, so I don't think it's that confusing for rust developer.  As for the test file, there are some `test.sh` scripts in rust projects.  The only complication is that `as-pect` looks for it in the root by default.  However, they both could live next to the contract nested in the larger project.
