### ISSUE TITLE
Oveflow and paranoid checks should be enabled by default for Rust contracts

### ISSUE THREAD

**Issue by miohtama** [near/create-near-app#498]
Rust supports overflow checks for integer arithmetics, however they are disabled by default for optimised builds.

[These checks are important because of an attack vector when dealing with user balances](https://ethereum.stackexchange.com/questions/8551/security-review-checklist-for-a-smart-contract).

Checks should be enabled in the generated `Cargo.toml` by default

https://github.com/near/create-near-app/blob/master/common/contracts/rust/Cargo.toml

More information here:

https://stackoverflow.com/q/64129432/315168

**Comment by frol** [comment]
@chadoh Could you, please, triage this issue?

**Comment by chadoh** [comment]
Is this sufficient, @frol? https://github.com/near/create-near-app/pull/502

**Comment by frol** [comment]
@chadoh Is it the only place where the Cargo.toml needs to be updated to reflect all the examples? I think we also need to go over our example contracts in Rust and update those.

**Comment by chadoh** [comment]
Yes, good call, I'll apply the same update added in #502 to all Rust examples

**Comment by chadoh** [comment]
Updated all examples and merged #502; thanks for the ideas @miohtama and the help @frol
