### ISSUE TITLE
create-near-app is broken

### ISSUE THREAD

**Issue by amgando** [near/create-near-app#533]
some more detail here: https://github.com/near/create-near-app/pull/532#issuecomment-723091776

after running `yarn dev` in the new project folder i see this, warnings re: assemblyscript dependencies then an infinite nodemon loop: 

![image](https://user-images.githubusercontent.com/24913/98439405-bed1be00-2102-11eb-9596-399068e547ca.png)

and Chloe captured this [on video here](https://youtu.be/Y5uMfj6ytn0?t=1202) after running `yarn dev`

![image](https://user-images.githubusercontent.com/24913/98439453-fe000f00-2102-11eb-9eaa-1522e6f84e76.png)

the most recent working version seems to be `1.2.2`

**Comment by chadoh** [comment]
Thanks for the report, @amgando, and sorry you ran into this, @chloethedev! I haven't yet been able to reproduce the bug. I am using node@12.14.1, npm@6.14.8, and yarn@1.22.5. I created a new app with `npx create-near-app ohno`, and then both `yarn build:contract` and `yarn dev` work for me.

What versions of these libraries are y'all using?

**Comment by amgando** [comment]
i'm able to repro with node 15 which made @willemneal say, out loud, "woah, slow down there cowboy" when he noticed.

would be good to fail fast if the version is "too new" as well as "too old" given this utility is intended for smooth onboarding. i'm assuming that's possible

**Comment by chadoh** [comment]
This has been fixed in [v1.3.2](https://github.com/near/create-near-app/releases/tag/v1.3.2). Please try it out with nodejs 15 and npm 7 and let me know if anything seems off!
