### ISSUE TITLE
.gitignore file never created

### ISSUE THREAD

**Issue by mikedotexe** [near/create-near-app#66]
This repo contains a `.gitignore` file, but it seems that in the publishing process of the generator, the file is stripped out.

[Similar thread here](https://github.com/npm/npm/issues/3763).

Expected behavior: an end user uses a command (like `npx create-near-app path/to/your/new-awesome-app`) and a `.gitignore` file exists in their project directory, making sure they don't add sensitive or unimportant files that may be pushed publicly.

**Comment by frol** [comment]
I have the same experience here. It is a minor papercut, but still annoying during a hackathon.

**Comment by mikedotexe** [comment]
linking discussion and eventual solution that will be in:
https://github.com/nearprotocol/create-near-app/pull/67

**Comment by mikedotexe** [comment]
fixed
