### ISSUE TITLE
dev deploy

### ISSUE THREAD

**Issue by blake41** [near/create-near-app#789]
The docs that get generated by create-near-app are pretty good.  They mention "Every smart contract in NEAR has its own associated account. When you run yarn dev, your smart contract gets deployed to the live NEAR TestNet with a throwaway account. When you're ready to make it permanent, here's how."

However, if you go through this process and then run yarn start. it doesn't work.  I realized this is because prestart runs near dev-deploy which generates the throwaway and has to be changed to run just deploy

**Comment by gagdiez** [comment]
this should be fixed in the latest release
