### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by GopherJ** [near/create-near-app#802]
Hi, it'll be good to have typescript

**Comment by mrrobot16** [comment]
It be amazing to have typescript support for the react template :)

**Comment by kulame** [comment]
i also need it

**Comment by AhanR** [comment]
I'd be interested in creating the typescript extension. Is anyone else working on this issue?

**Comment by gagdiez** [comment]
@AhanR nobody is working on it as far as I know

**Comment by AhanR** [comment]
Amazing, This will be my first PR could you walk me through how could I go about it?
Here's how I understand it so far :
>create a fork
>make changes in the template folder
>and then push to the repo?

**Comment by mrrobot16** [comment]
> Amazing, This will be my first PR, could you walk me through how could I go about it? Here's how I understand it so far :
> 
> * create a fork
> * make changes in the template folder
> * and then push to the repo?

@AhanR Amazing man, this is gonna be very useful for the NEAR Community.

**Comment by AhanR** [comment]
Hey, I was reading through the readme and saw the developer guidelines and I still cannot figure out how to set up my environment for this project.

I first cloned the repo, and duplicated the react folder under templates/frontend and ran `npm i` and `npm run start`. This produces an error message
```cmd
PS D:\Webdev\cloned repo\create-near-app-typescript-support\templates\frontend\react-ts> npm start

> my-near-app@1.0.0 start
> ./start.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
```

Can someone please help me set up the development environment? Thanks.

**Comment by chadoh** [comment]
@AhanR you may want to try [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install). This development setup has not been tested on Windows, and that probably won't be the last gotcha you run into.

**Comment by gagdiez** [comment]
this issue had been stalled long enough, thus proving we don't have the bandwidth to take on it

However, we have decided to use Next.js for the frontend, which is industry standard, and I assume has guides on how to use typescript

**Comment by laciferin2024** [comment]
WoW, we can't do typescript
